version: '3'
services:
    api:
        build: .
        image: oscarnewman/pipenv:3.6
        restart: always
        volumes:
            - .:/app
        ports:
            - 5000:5000
        depends_on:
            - db
            - redis
        environment:
            - DATABASE_URL=postgres://saythanks:password@db:5432/saythanks
            - REDIS_URL=redis://redis:6379/0
        links:
            - redis
            - db
        entrypoint: ['pipenv', 'run', 'flask', 'run', '--host=0.0.0.0']
    db:
        image: postgres:11-alpine
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=saythanks
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=saythanks
    redis:
        image: redis:3.0-alpine
        volumes:
            - 'redis:/data'
        ports:
            - 6379:6379

volumes:
    redis:
    pgdata:
