version: '3'
services:
  api:
    build: .
    image: oscarnewman/pipenv:3.6
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://root:root@db:5432/saythanks
      - REDIS_URL=redis
    links:
      - redis
      - db
  db:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=saythanks
  redis:
    image: redis:3.0-alpine
    volumes:
      - 'redis:/data'
    ports:
      - 6379:6379

volumes:
  redis:
  postgres:
