branch-defaults:
  master:
    environment: $CIRCLE_BRANCH-saythanks-backend
    group_suffix: null
global:
  application_name: saythanks-backend
  # branch: null
  # default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  # instance_profile: null
  # platform_name: null
  # platform_version: null
  # repository: null
  sc: git
  workspace_type: Application
