version: 2
jobs:
    deploy:
        working_directory: ~/app
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout

            - run:
                  name: Installing deployment dependencies
                  working_directory: /
                  command: |
                      sudo pip install awsebcli pipenv --upgrade
            - run:
                  name: Decrypt Files
                  working_directory: ~/app
                  command: |
                      mkdir -p ./keys
                      openssl aes-256-cbc -d -in secure/firebase_encrypted -out keys/firebase.json -k $FB_ENCRYPTION_KEY -nopad
            - run:
                  name: Lock dependences to requirements.txt and commit
                  working_directory: ~/app
                  command: |
                      pipenv lock -r > requirements.txt
            - run:
                  name: Migrate Database
                  working_directory: ~/app
                  command: |
                      pipenv install
                      pipenv run flask db upgrade
            - run:
                  name: Deploying
                  working_directory: ~/app
                  command: eb deploy -v --staged $CIRCLE_BRANCH-saythanks-api
            - run:
                  name: Deployment notification to Rollbar
                  command: |
                      # Notify rollbar
                      curl https://api.rollbar.com/api/1/deploy/ \
                      -F access_token=$ROLLBAR_KEY \
                      -F environment=production \
                      -F revision=$CIRCLE_SHA1 \
                      -F local_username=$CIRCLE_USERNAME \
                      -F comment='Deploy with bug'

workflows:
    version: 2
    build:
        jobs:
            - deploy:
                  filters:
                      branches:
                          only:
                              - master
