"""add top_up field to user

Revision ID: 0b66fde74eae
Revises: 7a54afb8c6f2
Create Date: 2019-04-22 17:49:08.905802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b66fde74eae'
down_revision = '7a54afb8c6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('top_up', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'top_up')
    # ### end Alembic commands ###
