"""transaction tables

Revision ID: 3816d9f71747
Revises: 6f5f09fe68c3
Create Date: 2019-02-25 15:57:38.798949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3816d9f71747'
down_revision = '6f5f09fe68c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_udpated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', postgresql.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('real_amount', sa.Integer(), nullable=False),
    sa.Column('stripe_charge_id', sa.Text(), nullable=True),
    sa.Column('stripe_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawal',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_udpated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', postgresql.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('real_amount', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.Text(), nullable=True),
    sa.Column('stripe_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_udpated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_account_id', postgresql.UUID(), nullable=True),
    sa.Column('dest_account_id', postgresql.UUID(), nullable=True),
    sa.Column('payable_id', postgresql.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dest_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['payable_id'], ['payable.id'], ),
    sa.ForeignKeyConstraint(['source_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('app', sa.Column('stripe_account_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'stripe_account_id')
    op.drop_table('payment')
    op.drop_table('withdrawal')
    op.drop_table('deposit')
    # ### end Alembic commands ###
