"""apps and payables

Revision ID: 6f5f09fe68c3
Revises: 6a9a4e210118
Create Date: 2019-02-25 15:29:22.684499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f5f09fe68c3'
down_revision = '6a9a4e210118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_udpated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', postgresql.UUID(), nullable=True),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_user',
    sa.Column('app_id', postgresql.UUID(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('payable',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_udpated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('app_id', postgresql.UUID(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('display_price', sa.Integer(), nullable=False),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('account', sa.Column('time_udpated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('account', 'time_updated')
    op.add_column('user', sa.Column('time_udpated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('user', 'time_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('user', 'time_udpated')
    op.add_column('account', sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('account', 'time_udpated')
    op.drop_table('payable')
    op.drop_table('app_user')
    op.drop_table('app')
    # ### end Alembic commands ###
