"""user nullable

Revision ID: 70fa9d7fdb16
Revises: 8e8bc4cae49a
Create Date: 2019-04-08 17:45:55.133327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fa9d7fdb16'
down_revision = '8e8bc4cae49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
