"""update payables with url

Revision ID: d95b8447a36e
Revises: 26c4b17e337c
Create Date: 2019-03-24 22:53:46.441630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95b8447a36e'
down_revision = '26c4b17e337c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('content_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'content_url')
    # ### end Alembic commands ###
